# Generated by Django 3.1.5 on 2021-04-23 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=20, null=True)),
                ('algo_config', models.CharField(default='Nothing yet', max_length=10000)),
                ('exp_style_config', models.CharField(default='Nothing yet', max_length=10000)),
                ('profile_items', models.CharField(default='Nothing yet', max_length=10000)),
                ('recommended_items', models.CharField(default='Nothing yet', max_length=10000)),
                ('feed_back_top_1', models.CharField(default='Nothing yet', max_length=10000)),
                ('feed_back_re_top_1', models.CharField(default='Nothing yet', max_length=10000)),
                ('feed_back_top_1_2', models.CharField(default='Nothing yet', max_length=10000)),
                ('feed_back_re_top_1_2', models.CharField(default='Nothing yet', max_length=10000)),
                ('feed_back_top_1_3', models.CharField(default='Nothing yet', max_length=10000)),
                ('feed_back_re_top_1_3', models.CharField(default='Nothing yet', max_length=10000)),
                ('num_exp_top_5_list', models.CharField(default='Nothing yet', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recsys_demo.question')),
            ],
        ),
    ]
