# Generated by Django 3.1.5 on 2021-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_items',
            field=models.CharField(default='Nothing yet', max_length=200),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='recommended_items',
            field=models.CharField(default='Nothing yet', max_length=200),
        ),
    ]
