# Generated by Django 3.0.8 on 2020-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(choices=[('ms', 'Master'), ('phd', 'P.h.D'), ('pd', 'Post P.h.D'), ('h', 'Professor')], default='ms', max_length=20)),
            ],
        ),
    ]
