# Generated by Django 3.1.5 on 2021-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('education', models.CharField(choices=[('master student', 'Master'), ('phd student', 'Ph.D'), ('post doc student', 'Post Ph.D'), ('higher', 'Professor')], default=None, max_length=20)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=None, max_length=20, null=True)),
                ('feed_back_1', models.CharField(default='Nothing yet', max_length=100)),
                ('feed_back_2', models.CharField(default='Nothing yet', max_length=100)),
            ],
        ),
    ]
