# Generated by Django 3.1.5 on 2021-04-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0002_auto_20210423_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_comments',
            field=models.CharField(default='Nothing yet', max_length=10000),
        ),
    ]
