# Generated by Django 3.1.5 on 2021-02-08 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0002_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='feed_back_1',
            field=models.CharField(default='Nothing yet', max_length=500),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='feed_back_2',
            field=models.CharField(default='Nothing yet', max_length=500),
        ),
    ]
