# Generated by Django 3.0.8 on 2020-09-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0003_userinfo_feed_back_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='feed_back_2',
            field=models.CharField(default='Nothing yet', max_length=100),
        ),
    ]
