# Generated by Django 3.1.5 on 2021-02-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0003_auto_20210208_0833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='feed_back_1',
            new_name='feed_back_list',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='feed_back_2',
            new_name='feed_back_re_top_1',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='feed_back_top_1',
            field=models.CharField(default='Nothing yet', max_length=500),
        ),
    ]
