# Generated by Django 3.1.5 on 2021-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0003_userinfo_user_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('autres', 'Autres')], default=None, max_length=20, null=True),
        ),
    ]
