# Generated by Django 3.1.5 on 2021-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0004_userinfo_feed_back_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.CharField(choices=[('ms', 'Master'), ('phd', 'P.h.D'), ('pd', 'Post P.h.D'), ('h', 'Professor')], default=None, max_length=20),
        ),
    ]
