# Generated by Django 3.1.5 on 2021-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0004_auto_20210218_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='feed_back_list',
            field=models.CharField(default='Nothing yet', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='feed_back_re_top_1',
            field=models.CharField(default='Nothing yet', max_length=10000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='feed_back_top_1',
            field=models.CharField(default='Nothing yet', max_length=10000),
        ),
    ]
