# Generated by Django 3.1.5 on 2021-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0005_auto_20210218_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='algo_config',
            field=models.CharField(default='Nothing yet', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='exp_style_config',
            field=models.CharField(default='Nothing yet', max_length=50),
        ),
    ]
