# Generated by Django 3.1.5 on 2021-04-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys_demo', '0006_auto_20210405_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='num_exp_top_1',
            field=models.CharField(default='Nothing yet', max_length=50),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='num_exp_top_5_list',
            field=models.CharField(default='Nothing yet', max_length=50),
        ),
    ]
